### ISSUE TITLE
'messages' of undefined

### ISSUE THREAD

**Issue by daimz** [center-key/gulp-w3c-html-validator#6]
If there are no errors the validator receives a message that is undefined and breaks:
`TypeError: Cannot read property 'messages' of undefined`

```
// HTML Validation
function validateHTML() {
  return gulp.src('_site/**/*.html')
    .pipe(htmlValidator())
    .pipe(htmlValidator.reporter())
    .pipe(gulp.dest('_site'));
};
```

Any ideas how I can get around this?

**Comment by pilafmon** [comment]
The error message implies that `response` is undefined:
https://github.com/center-key/gulp-w3c-html-validator/blob/master/html-validator.js#L94

However, I'm not sure how that would happen.  Is there more to the error message you're encountering?  Perhaps a line number or maybe a stack trace?
